# MultiDimensional(Cok Boyutlu) Arraylerin Elemanlarina Ulasmak

In [1]:
import numpy as np

#### 1'den 21'e kadar sirali ve 5 row 4 column olacak sekilde matrix olustur

In [2]:
arr = np.arange(1, 21).reshape(5, 4)

In [3]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [4]:
arr[0]

array([1, 2, 3, 4])

In [5]:
arr[4]

array([17, 18, 19, 20])

In [6]:
arr[0][3]

4

In [7]:
arr[4,3]

20

##### arr'in ndimension'u yani boyutu

In [8]:
arr.ndim

2

#### Dogrudan belirli index'e deger atamasi yapabiliriz

In [9]:
arr[0,0] = 666

In [10]:
arr

array([[666,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

#### 444.44 float degeri dogrudan int'e cast edilebildiginden tam kismi aldi

In [11]:
arr[0,1] = 444.44

In [12]:
arr

array([[666, 444,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

#### '32' degeri her ne kadar string olsa da int'e cast edilebilir yani string ici tam sayi

In [13]:
arr[0,2] = '32'

In [14]:
arr

array([[666, 444,  32,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

#### Ancak '32.3232' olarak deger vermeye kalkarsak string ici tam sayi olmadigindan hata verir

In [15]:
arr[0,3] = '32.3232'

ValueError: invalid literal for int() with base 10: '32.3232'

In [ ]:
arr

## Slice Indexing 

In [16]:
arr = np.arange(1, 21).reshape(4, 5)

In [17]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [18]:
arr[2]

array([11, 12, 13, 14, 15])

#### matrixin her bir rowuna gore indexleme yapiyor.

In [19]:
arr[1: 3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
arr[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
arr[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
arr[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [23]:
arr[::-1]

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [24]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### Sadece columndaki degerleri aldi

In [25]:
arr[:, 3]

array([ 4,  9, 14, 19])

In [26]:
arr[:, 1]

array([ 2,  7, 12, 17])

#### Sadece rowdaki degerleri aldi

In [27]:
arr[2, :]

array([11, 12, 13, 14, 15])

In [28]:
arr[0, :]

array([1, 2, 3, 4, 5])

In [30]:
arr[::-1]

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [33]:
arr[:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

In [29]:
arr[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])