# Fancy(Suslu) Indexing

### Fancy Indexing ile bir kac tane belirli index'deki elemanlari getir demis olacagiz.

In [1]:
import numpy as np

In [4]:
arr = np.arange(1, 15)

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Bulmak istedigimiz indexleri bir liste atadik

In [8]:
indexing = [1, 3, 2, 7, 5]

In [9]:
arr[indexing]

array([2, 4, 3, 8, 6])

## Multi Dimensional Arraylerde de gecerli bu kural

In [10]:
arr = np.arange(1, 13).reshape(3, 4)

In [11]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

arr[buradaki deger rowda indexing yapar -> arr[0:2] gibi    ,     buradaki deger columnda indexing yapar -> arr[, 2] gibi ]

Row'da 0'dan 3.index'e kadar 2. Column'daki degerleri getir

In [16]:
arr[0:3, 2]

array([ 3,  7, 11])

In [17]:
arr[0:2, 1:3]

array([[2, 3],
       [6, 7]])

Tum Row'lari tara, 0. ve 2. indexteki Column'lari getir.

In [22]:
arr[:, [0,2]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [23]:
array = np.arange(20).reshape(4,5)

In [24]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
indx1 = [1, 3, 2]

In [26]:
indx2 = [0, 4, 2]

index1 ve index2 deki kesisen degerleri array multi dimensional array'de getirdi


In [30]:
array[indx1, indx2]

array([ 5, 19, 12])