# Sub Array

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 21).reshape(5, 4)

In [3]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [8]:
b = arr[:2, :3]

In [9]:
b

array([[1, 2, 3],
       [5, 6, 7]])

#### Dimension'u:

In [10]:
b.ndim

2

In [11]:
b[0,0] = 100

In [12]:
b

array([[100,   2,   3],
       [  5,   6,   7]])

In [13]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

Goruldugu gibi arr Array'inin bir kismini b Array'ine atadik. Ancak b'de ki bir degisiklik arr Array'ini de etkiledi. Bunun sebebide direkt = operatoru ile atama islemi yapmak hafizada ayni yeri referans almasina olanak saglamaktadir. Bu sorunu cozmek icin copy() fonksiyonunu kullanmamiz lazim.

### Simdi de Sub Array'imizi copy() fonksiyonu ile olusturmaya calisalim...

In [27]:
arr = np.arange(1, 21).reshape(5, 4)

In [28]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

0. ve 1. indexteki rowlar ile, 0., 1. ve 2. column'lar arasindaki butun elemanlari b Array'ine kopyala

In [29]:
b = arr[:2, :3].copy()

In [30]:
b

array([[1, 2, 3],
       [5, 6, 7]])

In [31]:
b[0,0] = 100

In [32]:
b

array([[100,   2,   3],
       [  5,   6,   7]])

In [33]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])