# Any


Conditional expression'u Arraydeki her bir eleman icin uygular.

## All -> Hepsi
## Any -> Her Biri

In [1]:
import numpy as np

In [2]:
arr = np.arange(20).reshape(4,5)

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
filter = arr > 16

In [9]:
filter

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True]])

In [10]:
np.any(filter)

True

Bulundugu Axis'de sadece 1 tanesinin True olmasi sonucu True yapar!

In [15]:
np.any(filter, axis=0) # Vertical

array([False, False,  True,  True,  True])

In [16]:
np.any(filter, axis=1) # Horizontal

array([False, False, False,  True])