In [1]:
import numpy as np

In [4]:
arr = np.arange(0, 15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr[5]

5

In [6]:
arr[2: 7]

array([2, 3, 4, 5, 6])

In [7]:
arr[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

bir dizinin belirli araligindaki elemanlarin hepsine deger atama yaptik

In [13]:
arr[2: 7] = -1
arr

array([ 0,  1, -1, -1, -1, -1, -1,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
arr2 = np.arange(0, 10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

bir dizinin belirli bir bolumunu baska bir diziye asagidaki gibi atadik

In [16]:
sliceArr = arr2[2: 7]
sliceArr

array([2, 3, 4, 5, 6])

bir dizinin butun elemanlarina tek degeri atama

In [17]:
sliceArr[:] = 666
sliceArr

array([666, 666, 666, 666, 666])

sliceArr'i arr2'den parcalayip atamistik. Goruldugu gibi dizinin orijinali arr2'de degisti

In [19]:
arr2

array([  0,   1, 666, 666, 666, 666, 666,   7,   8,   9])

#### Simdi bu islemleri orijinal diziyi degistirmeden yapalim! 

In [20]:
exampleArr = np.arange(0, 15)

kopyalayacagimiz dizinin varsayilan degerleri degismemesi icin asagidaki gibi bir islem yapiyoruz

In [22]:
kopyaArr = exampleArr.copy()
kopyaArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
exampleArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

dizinin belli bir bolumunu baska diziye atadik

In [32]:
kopyaArrSlicing = kopyaArr[2: 7]

atadigimiz dizinin elemanlarini degistirdik

In [33]:
kopyaArrSlicing[:] = -111

#### Bir kısmı alınıp atanan dizi 

In [28]:
kopyaArrSlicing

array([-111, -111, -111, -111, -111])

#### copy() ile kopyaladigimiz dizi 

In [34]:
kopyaArr

array([   0,    1, -111, -111, -111, -111, -111,    7,    8,    9,   10,
         11,   12,   13,   14])

#### Ilk olusturdugumuz orj dizimiz 

Goruldugu gibi ilk dizimiz degismedi, degismemesi icin copy() ile kopyalamamiz lazim!

In [35]:
exampleArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Matrix

In [36]:
matrixArr = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [37]:
matrixArrCopy = np.array(matrixArr)

In [38]:
matrixArrCopy

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:
matrixArrCopy[0]

array([10, 20, 30])

In [44]:
matrixArrCopy[0][0] # Satir Sutun

10

In [45]:
matrixArrCopy[2, 2]

90

In [48]:
newArr = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]

In [49]:
newArr

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]]

In [50]:
newMatrix = np.array(newArr)

In [51]:
newMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Belirlenen satirlari getirme islemi

In [53]:
newMatrix[[0, 1, 4]]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])