# 2 Numpy dizisini birlestirme

2 veya daha fazla array'i birlestirebiliriz. np.concatenate([arr1, arr2, arr3...])

Birlestirilecek array'lerin Numpy Array'i olma zorunlulugu da yoktur.

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])

In [3]:
arr2 = np.array([6, 7, 8, 9, 10])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr2

array([ 6,  7,  8,  9, 10])

concatenation ile 2 array'i birlestirelim

In [6]:
np.concatenate([arr1, arr2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
liste = [11, 12, 13]

#### 2 tane Numpy Array'i 1 tane normal listeyi birlestirdik

In [8]:
np.concatenate([arr1, arr2, liste])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

#### Iclerinden birisi float ise;

In [9]:
l = [11, 12, 13, 14.5]

In [10]:
np.concatenate([arr1, arr2, l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. , 11. ,
       12. , 13. , 14.5])

Goruldugu gibi hepsini #float turune cast etmis oldu

#### Iclerinden birisi string ise;

In [11]:
l = [11, 12, '13', 14.4]

In [12]:
np.concatenate([arr1, arr2, l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14.4'], dtype='<U32')

Goruldugu gibi hepsini #string turune cast etti

### Tuple verirsek?

In [13]:
l = (11, 12, 13, 14, 15)

In [14]:
np.concatenate([arr1, arr2, l])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Goruldugu gibi hepsini ortak bir listede birlestirdi.