# Numpy Arrays

Numpy Array'leri homojen yani tek tip verilerden olusmali.

In [1]:
import numpy as np

In [2]:
arr = [10, 20, 30, 40]

Normal bir diziyi Numpy dizisi haline cevirme

In [3]:
np.array(arr)

array([10, 20, 30, 40])

In [4]:
matrix = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [5]:
matrix

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [7]:
np.array(matrix)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# arange

Normal range ile olusturdugumuz dizimiz

In [8]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Numpy dizisi turunde arange ile olusturdugumuz dizimiz

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

### zeros

Numpy dizisinin tum elemanlarinin 0 old. durumdur

In [11]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones

Numpy dizisinin tum elemanlarinin 1 old. durumdur

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((7, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

# linspace

belirlenen 2 parametre arasinda 3. parametre kadar aralik belirleyip bir Numpy dizisi olusturmaya yarar

In [26]:
np.linspace(0, 20, 10) # 0 ve 20 de dahil o.u bu araligi 10 esit parcaya bol

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

# eye

satir ve sututun esit oldugu durumlari 1 yapan matrix(birim matrix)'i olusturur

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

# random

In [17]:
np.random.randn(10)

array([ 0.62871664,  0.88353225, -0.27593447, -0.22346328, -1.19219636,
       -1.92350427, -0.36670335,  0.9496553 , -0.76093476, -0.58822309])

In [18]:
np.random.randn(5, 5)

array([[ 3.76744026, -1.50706992, -1.09231375, -1.3272111 , -1.36407385],
       [-1.7207967 , -0.35980218, -0.15941094,  0.30148028,  0.15359941],
       [ 0.71764431,  0.65459184, -0.16678779, -0.3247893 ,  2.04927718],
       [ 1.02638694,  0.42828411, -0.30800076, -0.53898109, -1.79559473],
       [ 0.59040361,  0.64554282, -0.90967642, -0.66257617, -0.44279668]])

7 tane 4*3'luk matris olusturur

In [19]:
np.random.randn(7, 4, 3)

array([[[ 0.6116159 , -0.25970745, -0.03392586],
        [ 0.21758322,  1.84109302, -0.34816822],
        [ 0.05753762, -1.00008416, -1.94045836],
        [-1.23908222,  0.24964193, -0.82507932]],

       [[-1.62441615,  1.39273091,  0.44202864],
        [ 0.93248216,  0.38443164,  0.37547533],
        [ 0.48057166, -0.97794094, -0.63921247],
        [-0.51016721,  0.62241109, -0.91150178]],

       [[-1.92081939, -0.20045866, -0.9494199 ],
        [ 0.16543717, -0.0535726 ,  1.52106707],
        [ 1.23136317,  0.56334106, -0.08119371],
        [-0.05779488, -0.464037  , -0.82188829]],

       [[ 1.52267926,  0.16400346, -0.23860054],
        [ 0.92123248, -0.19370248,  1.0563643 ],
        [ 1.37377113,  1.18110699,  0.40650588],
        [ 1.13287633,  1.01181534,  0.42468384]],

       [[ 0.62020262, -0.58866718,  2.79448068],
        [-1.58170564, -1.1773437 , -0.45872588],
        [-0.21450216, -1.04438488, -2.23849489],
        [ 0.60143814,  1.15274885, -1.5889075 ]],

       [[ 

0'dan 30'a kadar 8 tane random deger getir

In [28]:
np.random.randint(0, 30, 8)

array([ 2,  8,  0, 23, 22, 28, 25, 10])

In [30]:
np.random.randint(1, 10, (4, 3)) # 1 dahil 10 arasinda 4*3'luk matris olustur

array([[8, 1, 8],
       [7, 9, 6],
       [1, 1, 1],
       [4, 2, 3]])

# Numpy Dizi Methodlari

In [21]:
dizi = np.arange(30)

In [22]:
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

ust satirdaki dizi listemizin eleman sayisi 30 old. satir ve sutunlarinin carpimi 30'a esit olmasi gerekir

In [23]:
dizi.reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
dizi.reshape(6, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

alt satirda gorundugu gibi dizimizin orijinal durumu degismemektedir

In [25]:
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### Rastgele uretilen sayilardan toplamda kac tane uretildiklerini bulan kod 

In [40]:
d = {}
for _ in range(100):
    value = np.random.randint(1, 10)
    
    if value not in d:
        d[value] = 1
    else:
        d[value] += 1

In [41]:
d

{2: 10, 9: 9, 5: 16, 3: 13, 8: 9, 6: 14, 7: 12, 4: 8, 1: 9}