# SUM

Array icindeki value'leri toplar.

In [2]:
import numpy as np

In [3]:
arr = np.arange(1, 21).reshape(4,5)

In [4]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
np.sum(arr)

210

5'den kucuk arr Array'indeki degerleri toplattik.

In [8]:
np.sum(arr[arr < 5])

10

## Belirli Axis Uzerinde Sum Operatorunu Kullanmak

In [9]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### axis=0  ->  Vertical(Dikey) Olarak Toplar

### axis=1  ->  Hotizontal(Yatay) Olarak Toplar

In [31]:
np.sum(arr, axis=0) # Vertical-Dikey

array([34, 38, 42, 46, 50])

In [32]:
np.sum(arr, axis=1) # Horizontal-Yatay

array([15, 40, 65, 90])

6+1 = 7,   7+2 = 9

In [33]:
np.sum(arr[:2, :2], axis=0)

array([7, 9])

# Prod

Array uzerinde multiplication islemi yapar

In [4]:
arr2 = np.arange(1, 11).reshape(2,5)

In [5]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
np.prod(arr2)

3628800

## Belirli Axis'ler uzerinde Prod Operatoru

In [49]:
np.prod(arr2, axis=0)

array([ 6, 14, 24, 36, 50])

In [50]:
np.prod(arr2, axis=1)

array([  120, 30240])