# Normal Dagilimdan Orneklem Alalim

#### mean, standart sapma(std - standard deviation), array size(row, column)

In [1]:
import numpy as np

Ortalamasi = 1, Standart Sapmasi = 2, 5*4'luk bir matris olustur.

In [2]:
np.random.normal(1, 2, (5, 4))

array([[ 3.128308  ,  2.01598822,  1.35376823, -2.39179236],
       [ 3.49435984, -0.43065318,  1.64382068,  4.46141517],
       [ 3.64183191,  3.08397424,  1.75517307,  2.67145661],
       [ 1.21779396,  1.39032502, -2.39731586, -0.46700406],
       [ 0.07868838, -1.19123628, -0.89106149,  2.05131812]])

## Array Attributes

In [27]:
x = np.zeros((4, 7))

In [28]:
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [29]:
x.shape

(4, 7)

2 tane 3*5'lik multi dimensional array olusturduk

In [30]:
y = np.zeros((2, 3, 5))

In [31]:
y

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [32]:
y.shape

(2, 3, 5)

x'in kac tane parametre ile matrix olusturuldugunu verir. (4, 7)

In [33]:
x.ndim

2

y'nin kac tane parametre ile matrix olusturuldugunu verir. (2, 3, 5)

In [34]:
y.ndim

3