# Size Mismatch

In [1]:
import numpy as np

#### tek boyutlu listemiz

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
a

array([1, 2, 3, 4, 5])

#### iki boyutlu listemiz

In [4]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
x.size # x'in eleman sayisi

6

In [7]:
a.size # a'nin eleman sayisi

5

In [8]:
x.shape # x'in boyutu

(2, 3)

In [9]:
a.shape # a'nin boyutu tek boyutlu old icin satir ve sutundan soz edilemez

(5,)

### a ve x'i concatenate etmeye calisalim
## shape mismatch

In [10]:
np.concatenate([a,x])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

#### ustteki islem hata verir cunku biri matrix digeri tek boyutlu liste

### x'i concatenate etmeye calisalim

In [11]:
np.concatenate([x, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Goruldugu gibi x'i 2 defa alt alta yazdirdi

### Axis(Eksen) girerek x matrix'ini concatenate ettirelim 

In [12]:
np.concatenate([x, x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Goruldugu gibi;
axis=1 iken yatayda concatenate eder.
axis=0(Varsayilan) iken dikeyde concatenate eder.

In [13]:
np.concatenate([x, x], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])