# Sorting(Siralama)

In [1]:
import numpy as np

In [2]:
a = np.array([20, 30, 10, 5, 40, 60])

In [3]:
a

array([20, 30, 10,  5, 40, 60])

Bu np.sort(a) kod satiri a array'ini kalici siralamaz!!!

In [6]:
np.sort(a)

array([ 5, 10, 20, 30, 40, 60])

In [7]:
a

array([20, 30, 10,  5, 40, 60])

In [8]:
a.sort()

In [9]:
a

array([ 5, 10, 20, 30, 40, 60])

#### np.sort(a) -> a'yi kalici guncellemez!
#### a.sort() -> a'yi kalici gunceller

## argsort

#### a'yi siralar ancak siraladiktan sonra index'lerini dondurur

In [14]:
a = np.array([2, 4, 1, 2, 5, 7])

In [15]:
a

array([2, 4, 1, 2, 5, 7])

##### 1 -> 2. index
##### 2 -> 0. index
##### 2 -> 3. index
##### 4 -> 1. index
##### 5 -> 4. index
##### 7 -> 5. index

### goruldugu gibi degerleri siraladi ve original array'deki sayilarin bulunduklari indexlerini dondurdu

In [16]:
a.argsort()

array([2, 0, 3, 1, 4, 5], dtype=int64)