# Splitting

In [1]:
import numpy as np

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### split metodu bir arrayi veya listeyi parcalamaya/bolmeye yarar

arr dizisinin 3. indisinin basina bir centik at ve 5. indisinin basina bir centik at

In [14]:
np.split(arr, [3, 5]) # 3 ve 5 index degeleri

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

## Split'in sonucunu baska bir degiskene esitleme

In [15]:
a, b = (1, 10)

In [24]:
print(a)
print(b)

1
10


In [28]:
x, y, z = np.split(arr, [4, 6])

In [29]:
print(x)
print(y)
print(z)

[0 1 2 3]
[4 5]
[6 7 8 9]


## VSplit(Vertical Split)

0'dan 20'ye kadar sirali liste olustur ve bunu da(reshape(2, 10)) 2*10'luk bir matrix yap

In [38]:
a = np.arange(20).reshape(2, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [45]:
np.vsplit(a, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [53]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## HSplit(Horizontal Split)

In [54]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [65]:
np.hsplit(a, [4])

[array([[ 0,  1,  2,  3],
        [10, 11, 12, 13]]),
 array([[ 4,  5,  6,  7,  8,  9],
        [14, 15, 16, 17, 18, 19]])]

In [73]:
np.hsplit(a, [3])[1]

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19]])