# Numpy Operasyonlar

In [2]:
import numpy as np

1'den 100'e kadar 20 tane rastgele int deger uretme

In [6]:
arr = np.random.randint(1, 100, 20)

In [7]:
arr

array([96, 28,  4, 61, 49, 87, 83, 22, 66, 46,  7, 24, 66,  2, 24, 64, 79,
       91, 17, 48])

In [8]:
arr > 24

array([ True,  True, False,  True,  True,  True,  True, False,  True,
        True, False, False,  True, False, False,  True,  True,  True,
       False,  True])

arr dizisinde 24'den buyuk olanlari copyArr dizine kopyaladik

In [15]:
copyArr = arr > 24

In [16]:
copyArr

array([ True,  True, False,  True,  True,  True,  True, False,  True,
        True, False, False,  True, False, False,  True,  True,  True,
       False,  True])

Sadece 24'den buyuk olanlari getirdi

In [17]:
arr[copyArr]

array([96, 28, 61, 49, 87, 83, 66, 46, 66, 64, 79, 91, 48])

### Bu islemi su sekildede yapabilirdik...

In [18]:
arr[arr > 24]

array([96, 28, 61, 49, 87, 83, 66, 46, 66, 64, 79, 91, 48])

### Bir diziyi kendisiyle toplayalim

In [19]:
arr + arr

array([192,  56,   8, 122,  98, 174, 166,  44, 132,  92,  14,  48, 132,
         4,  48, 128, 158, 182,  34,  96])

### Bir diziyi kendisiyle carpalim

In [20]:
arr * arr

array([9216,  784,   16, 3721, 2401, 7569, 6889,  484, 4356, 2116,   49,
        576, 4356,    4,  576, 4096, 6241, 8281,  289, 2304])

Goruldugu gibi yapilan degisiklikler atama yapmadigimiz icin kalici degiller

In [23]:
arr

array([96, 28,  4, 61, 49, 87, 83, 22, 66, 46,  7, 24, 66,  2, 24, 64, 79,
       91, 17, 48])

### Bir dizinin tum elemanlarinin Karekokunu alalim

In [24]:
np.sqrt(arr)

array([9.79795897, 5.29150262, 2.        , 7.81024968, 7.        ,
       9.32737905, 9.11043358, 4.69041576, 8.1240384 , 6.78232998,
       2.64575131, 4.89897949, 8.1240384 , 1.41421356, 4.89897949,
       8.        , 8.88819442, 9.53939201, 4.12310563, 6.92820323])

Bir dizinin en kucuk elemani

In [25]:
np.min(arr)

2

Bir dizinin en buyuk elemani

In [26]:
np.max(arr)

96