# Conditional Indexing - Filter

In [4]:
import numpy as np

In [7]:
arr = np.arange(1, 10)

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Boyle bir kullanim geriye Boolean bir Array dondurur.

In [12]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False])

Boyle bir kullanimda ise Array icinde 5'den kucuk olan degerleri getirir

In [14]:
arr[arr < 5]

array([1, 2, 3, 4])

### Condition expression'u bir value'ye esitleyerekde yapabiliriz;

In [15]:
filter = arr < 5

In [16]:
filter

array([ True,  True,  True,  True, False, False, False, False, False])

In [17]:
arr[filter]

array([1, 2, 3, 4])

### Simdide 2 farkli Array'in ayni olan degerlerini filter ile bulalim...

In [18]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
b = np.array([1, 2, 4, 6, 7, 9, 11, 13, 9])

In [35]:
b

array([ 1,  2,  4,  6,  7,  9, 11, 13,  9])

Boyle bir Conditional ifadesi Bool olarak geri doner

In [36]:
arr == b

array([ True,  True, False, False, False, False, False, False,  True])

In [37]:
arr[arr == b]

array([1, 2, 9])

In [38]:
b[b == arr]

array([1, 2, 9])

Goruldugu gibi ayni index'deki ayni degerleri bize getirdi.

## Normal Python'da kullandigimiz and, or kavramlari Numpy'da kullanamiyoruz. and = &   ,   or = |    operatorleri kullanilir.

Bu kod satiri hata dondurur.

In [40]:
(arr < 3) or (arr > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Bool Array'i dondurur.

In [41]:
(arr < 3) | (arr > 5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

Normal degerler iceren Array dondurur.

In [44]:
arr[(arr < 3) | (arr > 5)]

array([1, 2, 6, 7, 8, 9])

### Conditional Expression'u bir value'ye esitleyerekde filter yapabiliriz.

In [45]:
filter = (arr < 3) | (arr > 5)

In [46]:
filter

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [47]:
arr[filter]

array([1, 2, 6, 7, 8, 9])

### Eger Conditional Expression'unun Degilini alacaksak   ~ (Tilda) isaretini getiriyoruz...

3'den buyuk veya esit, 5'den kucuk veya esit degerleri getirir

In [49]:
arr[~filter]

array([3, 4, 5])