# All

Array'in tum elemanlari verilen conditional'i sagliyor mu?

In [1]:
import numpy as np

In [4]:
arr = np.arange(20).reshape(4, 5)

In [5]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Kosulumuz;

In [6]:
filter = arr > -1

In [7]:
filter

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [8]:
arr[filter]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
np.all(filter)

True

In [10]:
np.all(arr > 5)

False

### All Fonksiyonu Array'deki tum kosullari kapsar. 1 tanesi bile false olursa false dondurur.

#### Simdi de Axis'ler uzerinde All Fonk. uygulayalim

In [25]:
filter = arr > 3

In [26]:
filter

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

Vertical olarak;

In [27]:
np.all(filter, axis=0)

array([False, False, False, False,  True])

Horizontal olarak;

In [28]:
np.all(filter, axis=1)

array([False,  True,  True,  True])