# Numpy Dizisinin Veri Tipini Manuel Verme

In [1]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6.4])

Sadece 1 tane float olmasina ragmen butun elemanlari int'den float'a convert etti.

In [20]:
arr

array([1. , 2. , 3. , 4. , 5. , 6.4])

Usttekiyle ayni dizi ancak biz hangi tipte olacagini manuel verdik

In [21]:
arr2 = np.array([1, 2, 3, 4, 5, 6.4], dtype='int32')

In [22]:
arr2

array([1, 2, 3, 4, 5, 6])

In [23]:
x = np.array(['4.2'], dtype = 'float')

In [37]:
x

array([4.2])